development:
  adapter: sqlite3
  database: db/tknbn-dev.sqlite3
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: db/tknbn-test.sqlite3
  pool: 5
  timeout: 5000

production:
  adapter: sqlite3
  database: db/tknbn.sqlite3
  pool: 5
  timeout: 5000
